### ISSUE TITLE
raider meme/flavour text to 'vagabond'

### ISSUE THREAD

**Issue by newwby** [MrSamuelStreamer/RPGFantasyFlavourMod#37]
rename suggestion based on faction relationship screen ('we are raiders -50')

**Comment by feldoh** [comment]
hmmm, I like the idea of renaming raider but I'm not sure about vagabond because that implies no home, but they do have a home, the inn and the questing guild. I think vagabond would be a great one for nomadic. I feel like this is more "are we the bad guys?" perhaps? Sort of implying they're questioning if by going out and attacking places they are the bad guys, what do you think?

**Comment by newwby** [comment]
True, I was approaching it from a 'this is how other people view us' way. Like less civilised for questing rather than working on the homestead. It definitely fits nomadic better.

Perhaps 'looter' or something? Like it's frowned upon to be ransacking sites and going out to take stuff, but the meme moodlets are all things like 'it's been x days since we got any loot!'
Looter also still keeps the raider theme for people playing a traditional raider version.

**Comment by feldoh** [comment]
I like that, looter it is!
